name: Fullstack CI/CD to IBM Cloud

on:
  push:
    branches: [ "main" ]

env:
  # Ambil Secrets dari GitHub
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
  
  # Variabel untuk Terraform
  TF_VAR_ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
  TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  TF_VAR_dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  TF_VAR_resource_group: "itz-wxo-697c4652010cfefe9db664"
  TF_VAR_project_name: "nyoba-cicd-joy2" 
  TF_VAR_region: "us-south"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- STEP 1: DOCKER BUILD & PUSH ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/backend-app:latest
          platforms: linux/amd64

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/frontend-app:latest
          platforms: linux/amd64
          build-args: REACT_APP_BACKEND_URL=https://placeholder-backend.cloud

      # --- STEP 2: TERRAFORM DEPLOY ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve