name: IBM Cloud

on:
  push:
    branches: [ "main" ]

env:
  # Credentials & Config
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
  
  # Variabel untuk Terraform
  TF_VAR_ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
  TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  TF_VAR_dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  TF_VAR_resource_group: "itz-wxo-697c4652010cfefe9db664"
  TF_VAR_project_name: "nyoba-cicd-joy2"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- STEP 1: DOCKER BUILD & PUSH ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/backend-app:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          # Note: Kita tidak bisa inject URL Backend di sini secara dinamis karena Backend belum ada URL-nya saat pertama kali deploy.
          # Pastikan URL backend sudah di-hardcode di App.js seperti solusi kita sebelumnya.
          tags: ${{ env.DOCKERHUB_USERNAME }}/frontend-app:latest

      # --- STEP 2: TERRAFORM DEPLOY ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan